feat(PropTypes): Add PropTypes definitions
in-your-saas/material-ui-theme-editor pull request #4
Opened 2018-11-09 15:15 UTC by CHBresser

Added PropTypes w/ Default Props where needed.

2018-11-09 16:57 UTC, CHBresser commented
First PR let me know if I need to do anything else.

2018-11-09 17:09 UTC, jdrouet requested changes
Thank you for your contribution. I really appreciate it. But I'd some improvements to your PR.
- Putting the `propTypes` and `defaultProps` as static class properties
- Removing the double quotes
- Merge your 2 commits

2018-11-09 17:09 UTC, jdrouet commented on src/component/color-edition-list-item.js
> +ColorEditionListItem.propTypes = {
Considering that this component is a class, the `propTypes` and `defaultProps` should probably be set as a static class property

2018-11-09 17:09 UTC, jdrouet commented on src/component/color-bubble.js
> +import PropTypes from "prop-types";
Could you change all the double quotes by single quotes?

2018-11-09 17:09 UTC, jdrouet commented on src/component/color-bubble.js
> +ColorBubble.propTypes = {
Same than for `ColorEditionListItem`

2018-11-09 17:42 UTC, CHBresser commented on src/component/color-edition-list-item.js
> +ColorEditionListItem.propTypes = {
Done.

2018-11-09 17:42 UTC, CHBresser commented on src/component/color-bubble.js
> +import PropTypes from "prop-types";
Done.

2018-11-09 17:42 UTC, CHBresser commented on src/component/color-bubble.js
> +ColorBubble.propTypes = {
Done

2018-11-09 17:43 UTC, CHBresser commented
I am unaware of how to merge my commits. All the results on google seem to imply that you squash the commits when you merge the PR.

2018-11-09 20:28 UTC, CHBresser commented
Not sure what the conflict is now on package.json

2018-11-10 23:42 UTC, jdrouet commented
@CHBresser the procedure is the following.
- First move your commits to a different branch, it will be easier to pull our repo.
- then synchronise your repo with ours
- then rebase your branch to master
- then delete your last commit that might be useless due to the rebase
- squash the commits refering to the prop types

Also, I added the a linter on the project, so please take care that everything is ok, otherwise circleci won't let us merge your PR

2018-11-13 15:51 UTC, closed without merging